[project]
name = "corporesano"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "giolendius", email = "155963300+giolendius@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "plotly>=7.0.0",
]

[project.scripts]
corporesano = "corporesano:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
